---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  annotations:
    cert-manager.io/inject-ca-from: "$(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)"
    controller-gen.kubebuilder.io/version: "v0.3.0"
  creationTimestamp: null
  name: "clusterclaims.claim.tmax.io"
spec:
  additionalPrinterColumns:
  - JSONPath: ".status.phase"
    name: "Status"
    type: "string"
  - JSONPath: ".status.reason"
    name: "Reason"
    type: "string"
  - JSONPath: ".metadata.creationTimestamp"
    name: "Age"
    type: "date"
  group: "claim.tmax.io"
  names:
    kind: "ClusterClaim"
    listKind: "ClusterClaimList"
    plural: "clusterclaims"
    shortNames:
    - "cc"
    singular: "clusterclaim"
  scope: "Namespaced"
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema"
      properties:
        apiVersion:
          description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.apiVersion"
          type: "string"
        kind:
          description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.kind"
          type: "string"
        metadata:
          type: "object"
        spec:
          description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec"
          properties:
            clusterName:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.clusterName"
              type: "string"
            masterNum:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.masterNum"
              type: "integer"
            masterType:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.masterType"
              type: "string"
            provider:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.provider"
              type: "string"
            region:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.region"
              type: "string"
            sshKey:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.sshKey"
              type: "string"
            version:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.version"
              type: "string"
            workerNum:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.workerNum"
              type: "integer"
            workerType:
              description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.spec.properties.workerType"
              type: "string"
          required:
          - "clusterName"
          - "masterNum"
          - "masterType"
          - "provider"
          - "region"
          - "sshKey"
          - "version"
          - "workerNum"
          - "workerType"
          type: "object"
        status:
          description: "%clusterclaims.yaml.spec.validation.openAPIV3Schema.properties.status"
          properties:
            message:
              type: "string"
            phase:
              enum:
              - "Awaiting"
              - "Admitted"
              - "Success"
              - "Rejected"
              - "Error"
              - "Deleted"
              type: "string"
            reason:
              type: "string"
          type: "object"
      type: "object"
  version: "v1alpha1"
  versions:
  - name: "v1alpha1"
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
